### ISSUE TITLE
"Updating error code" in the logs

### ISSUE THREAD

**Issue by Guyohms** [claudegel/sinope-130#127]
Since the last release, I get this error several times by hours:
```
WARNING (SyncWorker_1) [custom_components.neviweb130.climate] Updating error code: {'referenceSensor': 'ok', 'compensationSensor': 'ok', 'airSensor': 'ok', 'wireSensor': 'ok', 'currentOverload': 'ok', 'thermalOverload': 'ok', 'loadError': 'ok', 'endOfLife': False}
```

![image](https://user-images.githubusercontent.com/44414660/208976747-96087ec8-83e7-4eb2-944b-1aa2f7ed44e0.png)

**Comment by claudegel** [comment]
What is your thermostat model and firmware

**Comment by claudegel** [comment]
OK It's not an error it's just debug I added because there are many difference in error code between each thermostat type
you can just comment out the line 1010 by putting a # in front of it to stop that message in custom_components/neviweb130/climate.py.
`#    _LOGGER.warning("Updating error code: %s",device_error_code)`
I'll make a new release that will remove that logging soon.

**Comment by Guyohms** [comment]
Thanks, it's not doing any harm, I will wait for the next release 

Merci Claude !
