### ISSUE TITLE
Unknown error for neviweb130 climate.

### ISSUE THREAD

**Issue by ijustlikeit** [claudegel/sinope-130#79]
**Hi Claude:  Got the following in my logs: today**

Logger: custom_components.neviweb130.climate
Source: custom_components/neviweb130/climate.py:740
Integration: Sinope Neviweb130 ([documentation](https://github.com/claudegel/sinope-130))
First occurred: 12:42:05 PM (1 occurrences)
Last logged: 12:42:05 PM

Unknown error for neviweb130 climate TH1310WF: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': 'a4cf12fffe83cdd0'}}}... Report to maintainer.

**and**

Logger: custom_components.neviweb130.climate
Source: custom_components/neviweb130/climate.py:728
Integration: Sinope Neviweb130 ([documentation](https://github.com/claudegel/sinope-130))
First occurred: 12:35:33 PM (2 occurrences)
Last logged: 12:36:03 PM

Error in reading device neviweb130 climate Flextherm FLP55: ({'errorCode': 'ReadTimeout'})
Error in reading device neviweb130 climate TH1310WF: ({'errorCode': 'ReadTimeout'})

The two devices still appear to be working though.

**Comment by claudegel** [comment]
Hi Don, DVCUNVLB is device unavailable. Neviweb is telling you that it can reach the device to update data.'
errorCode': 'ReadTimeout' is the response you got from Neviweb because it can't reach the two thermostat.
Both error are comming from Neviweb.The first one is because Neviweb cannot reah your network to talk to the wifi devices. The second is when Neviweb send request to the devices but it didn't get any answer before the timeout period.
This is a network problem or a firewall problem. Did you change anything in your network ?

**Comment by ijustlikeit** [comment]
Thanks for the explanation.  My network has not changed but has been up and down sporadically today, so that would explain the  timeouts.  I think that this fully explains the messages. I closing this issue.  Thanks again Claude!!

**Comment by claudegel** [comment]
I'll add more info in the code regarding those messages.
